openapi: 3.0.0
info:
  title: Mercado Livre Middleware API
  version: 0.0.1
  description: REST API for search products at mercado livre
servers:
  - url: http://localhost:8080/
    description: Local development server
paths:
  /:
    get:
      responses:
        200:
          description: OK
